export const FETCH_FORECAST_WEATHER_DATA = 'FETCH_FORECAST_WEATHER_DATA'
export const FETCH_HISTORIC_WEATHER_DATA = 'FETCH_HISTORIC_WEATHER_DATA'
export const POST_HISTORIC_DATA = 'POST_HISTORIC_DATA'